# Generated by Django 3.1.1 on 2020-09-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200920_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
