# Generated by Django 3.1.1 on 2020-09-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('Photoshop', 'Photoshop'), ('Lightroom', 'Lightroom')], default='Photoshop', max_length=255),
            preserve_default=False,
        ),
    ]
