# Generated by Django 3.1.1 on 2020-09-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200916_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='core.Item'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
